version: '3.7'

services:
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

    environment:
      MYSQL_ROOT_PASSWORD: 4O7d9.jk #example
      MYSQL_DATABASE: database

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
    depends_on:
      - python

  python:
    build:
      context: .
      dockerfile: DockerfilePython
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 4O7d9.jk