version: '3.7'

services:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_DATABASE: database

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: database
 