version: '3.7'

services:

####### PARA LLEGAR AL 5

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - database:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: 4O7d9.jk #example
      MYSQL_DATABASE: database

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
    depends_on:
      - python

  python:
    build:
      context: .
      dockerfile: DockerfilePython
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app


####### IMAGENES ADICIONALES

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 4O7d9.jk

  cadvisor:
    image: google/cadvisor:latest
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

volumes:
  database: