version: '3.7'

services:
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: database

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
    depends_on:
      - python

#  python:
#    image: python:3.8
#    restart: always
#    volumes:
#      - 
#    working_dir: /app
#    command: tail -f /dev/null
#    depends_on:
#      - db

  python:
    build:
      context: .
      dockerfile: DockerfilePython
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app
#  web:
#    image: web
#    environment:
#      - ALLOW_OVERRIDE=true
#    ports:
#      - "80:80"
#    links:
#      - db
#    volumes:
#      - ./app:/var/www/html/


#  phpmyadmin:
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 8081:80
#    environment:
#      PMA_ARBITRARY: 1
#      MYSQL_DATABASE: database